export const retry = {
  'name': 'catch',
  'operatorType': 'error handling'
};
